title: Brian's Awesome test site
slug: config
destination: _default
cascade:
  - type: aliases
    _target:
      kind: section
module:
  imports:
    - path: github.com/theNewDynamic/hugo-module-tnd-netlifycms
  mounts:
    - source: content/admin
      target: content/admin
    - source: layouts
      target: layouts
    - source: static
      target: static
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content/admin
      target: data
      excludeFiles: /**.md
    - source: content/admin/configuration
      target: data
      excludeFiles: /**.md
    - source: content/admin/data
      target: data
      excludeFiles: /**.md
    - source: content/admin/collections
      target: data
      excludeFiles: /**.md
    - source: content/admin/fields
      target: data
      excludeFiles: /**.md
    # - source: content/admin/archetypes/data
    #   target: data
      # excludeFiles: /**.md
    - source: content/admin/content
      target: data
      excludeFiles: /**.md
    # - source: content/admin/layouts/data
    #   target: data
    #   excludeFiles: /**.md
    # - source: content/admin/themes/data
    #   target: data
    #   excludeFiles: /**.md
