module:
  imports:
  - path: github.com/theNewDynamic/hugo-module-tnd-netlifycms
  mounts:
  - source: data
    target: data
  - source: content
    target: content
  - source: static
    target: static
