destination: _default
slug: config
module:
  imports:
    - path: github.com/theNewDynamic/hugo-module-tnd-netlifycms
    - path: github.com/kaushalmodi/hugo-bare-min-theme
  mounts:
    - source: data
      target: data
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: admin-collections/data
      target: data
    - source: admin-fields/data
      target: data
    - source: admin-hugo/data
      target: data
      
