widget: list
label: Cascade
name: cascade
required: false
types: 
  - name: aliases
    fields: 
      - import: field hugo-cascade-target
        field_type: import
      - import: field hugo-content-aliases
        field_type: import
  - name: audio
    fields: 
      - import: field hugo-cascade-target
        field_type: import
      - import: field hugo-content-audio
        field_type: import
  - name: date
    fields: 
      - import: field hugo-cascade-target
        field_type: import
      - import: field hugo-content-date
        field_type: import
  - name: description
    fields: 
      - import: field hugo-cascade-target
        field_type: import
      - import: field hugo-content-description
        field_type: import
        