name: outputFormats
label: Output Formats
widget: object
field_type: object
hint: "[Edit outputFormats](#/collections/hugo-config-objects/entries/outputFormats)"
required: false
collapsed: true
fields:
  - field_type: import
    import: field hugo-config-_merge