label: caches
name: caches
widget: object
field_type: object
required: false
collapsed: true
fields:
  - field_type: import
    import: field hugo-config-_merge 
  - field_type: import
    import: field hugo-config-cachetype
    extend:
      name: assets
      label: assets
  - field_type: import
    import: field hugo-config-cachetype
    extend:
      name: getcsv
      label: getcsv
  - field_type: import
    import: field hugo-config-cachetype
    extend:
      name: getjson
      label: getjson
  - field_type: import
    import: field hugo-config-cachetype
    extend:
      name: images
      label: images
  - field_type: import
    import: field hugo-config-cachetype
    extend:
      name: modules
      label: modules
