# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: fieldSets
identifier_field: name
label: Field Sets
label_singular: Field Set
collection_type: folder
description: "Create a list of fields to import to collections together. Syntax: import: set {{filename}}.fields"
folder: "data/netlifycms/sets"
fields:
  - field_type: import
    import: field nc-field-name
  - field_type: import
    import: field nc-collection-fields
create: true
publish: true
hide: false
delete: true
format: yml
extension: yml
editor:
  preview: true
