# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: field_types
identifier_field: name
label: Field Types
label_singular: Field Type
description: Field Types are object fields for obtaining fields lists stored in `nc-collection-fields.yml`, etc. 
folder: "data/netlifycms/types"
collection_type: folder
fields:
  - field_type: import
    import: field nc-field-name
  - field_type: import
    import: field nc-field-label
  - field_type: import
    import: field nc-field-widget
    extend: 
      default: object
  - field_type: import
    import: field nc-field-fields
create: false
publish: false
hide: false
delete: false
format: yml
extension: yml
editor:
  preview: true
summary: "{{label}}"
