# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: color_fields
identifier_field: name
label: Color Fields
label_singular: Color Field
description: |+
  The color widget translates a color picker to a color string.
folder: "data/netlifycms/fields"
collection_type: folder
fields:
  - import: field nc-field-name
    field_type: import
  - import: field nc-field-label
    field_type: import
  - import: field nc-field-widget
    field_type: import
    extend:
      default: color
  - import: field nc-field-field_type
    field_type: import
    extend:
      default: color
  - import: field nc-field-required
    field_type: import
  - import: field nc-field-default
    field_type: import
    extend: 
      widget: color
  - import: field nc-field-hint
    field_type: import
  - import: field nc-field-allowInput
    field_type: import
  - import: field nc-field-enableAlpha
    field_type: import
filter:
  field: field_type
  value: color
create: true
publish: false
hide: false
delete: true
format: yml
extension: yml

editor:
  preview: true
summary: "{{filename}}"
