# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: fields
label: Fields
label_singular: Field
folder: data/netlifycms/fields
fields:
  - field_type: import
    import: field nc-field-name
  - field_type: import
    import: field nc-field-label
  - field_type: import
    import: field nc-field-widget
  - field_type: import
    import: field nc-field-field_type
  - field_type: import
    import: field nc-field-hint
  - field_type: import
    import: field nc-field-default
  - field_type: import
    import: field nc-field-options
identifier_field: name
sortable_fields: ['{{fields.filename}}']
collection_type: folder
description: Create new fields using the "Quick Add" button at the top of the
  page. Use this list to quickly view and edit common options for your fields.
  The preview link will open the same field in a more specific editor for its
  type.
format: yml
extension: yml
create: true
hide: false
delete: false
slug: "{{namespace}}-{{component}}-{{slug}}"
preview_path: structure/collections/{{field_type}}/entries/{{slug}}
editor:
  preview: true
summary: "{{filename}}"
view_filters:
  - label: Hugo Configs
    field: namespace
    pattern: hugo
  - label: Config Options
    field: component
    pattern: config
  - label: Collection Options
    field: component
    pattern: collection
  - label: Field Options
    field: component
    pattern: field
view_groups:
  - label: Component
    field: component
