# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: list_variable_types_fields
identifier_field: name
label: List Variable Types Fields (BETA)
label_singular: List Variable Types Field (BETA)
collection_type: folder
description: >
  This beta feature replaces the fields field with the types field. Each type is
  an object field with its own set of fields. The fields field is a list variable types field.
folder: "data/netlifycms/fields"
fields:
  - import: field nc-field-name
    field_type: import
  - import: field nc-field-label
    field_type: import
  - import: field nc-field-types
    field_type: import
  - import: field nc-field-widget
    field_type: import
    extend:
      default: list
  - import: field nc-field-field_type
    field_type: import
    extend:
      default: list_variable_types
  - import: field nc-field-label_singular
    field_type: import
  - import: field nc-field-allow_add
    field_type: import
  - import: field nc-field-collapsed
    field_type: import
  - import: field nc-field-summary
    field_type: import
  - import: field nc-field-minimize_collapsed
    field_type: import
  - import: field nc-field-typeKey
    field_type: import
  - import: field nc-field-required
    field_type: import
  - import: field nc-field-hint
    field_type: import
  - import: field nc-field-comment
    field_type: import
filter:
  field: field_type
  value: list_variable_types
create: true
publish: false
hide: false
delete: true
format: yml
extension: yml

editor:
  preview: true
summary: "{{filename}}"

