# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: Markdown Fields
identifier_field: name
label: Markdown Fields
label_singular: Markdown Field
collection_type: folder
description: >
  The markdown widget provides a full fledged text editor allowing users to format text with features such as headings and blockquotes. Users can change their editing view with a handy toggle button.

  Please note: If you want to use your markdown editor to fill a markdown file contents after its frontmatter, you'll have to name the field body so the CMS recognizes it and saves the file accordingly.
folder: "data/netlifycms/fields"
fields:
  - import: field nc-field-name
    field_type: import
  - import: field nc-field-label
    field_type: import
  - import: field nc-field-widget
    field_type: import
    extend:
      default: string
  - import: field nc-field-required
    field_type: import
  - import: field nc-field-default 
    field_type: import
    extend:
      widget: markdown
  - import: field nc-field-hint 
    field_type: import
  - import: field nc-field-comment 
    field_type: import
  - import: field nc-field-pattern  
    field_type: import
  - import: field nc-field-minimal
    field_type: import
  - import: field nc-field-buttons
    field_type: import
  - import: field nc-field-editor_components
    field_type: import
  - import: field nc-field-modes
    field_type: import
  - import: field nc-field-sanitize_preview
    field_type: import
filter:
  field: field_type
  value: markdown
create: true
publish: false
hide: false
delete: true
format: yml
extension: yml

editor:
  preview: true
summary: "{{filename}}"

