# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: Map Fields
identifier_field: name
label: Map Fields
label_singular: Map Field
collection_type: folder
description: >
  The map widget allows you to edit spatial data using an interactive map. Spatial data for a single piece of geometry saves as a GeoJSON string in WGS84 projection.
folder: "data/netlifycms/fields"
fields:
  - import: field nc-field-name
    field_type: import
  - import: field nc-field-label
    field_type: import
  - import: field nc-field-widget
    field_type: import
    extend:
      default: map
      widget: hidden
  - import: field nc-field-decimals
    field_type: import
  - import: field nc-field-type
    field_type: import
  - import: field nc-field-required
    field_type: import
  - import: field nc-field-default
    field_type: import
    extend: 
      hint: accepts a GeoJSON string containing a single geometry; defaults to an empty string
filter:
  field: field_type
  value: map
create: true
publish: false
hide: false
delete: true
format: yml
extension: yml

editor:
  preview: true
summary: "{{filename}}"

