# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: Number Fields
identifier_field: name
label: Number Fields
label_singular: Number Field
collection_type: folder
description: >
  The number widget uses an HTML number input, saving the value as a string, integer, or floating point number.
folder: "data/netlifycms/fields"
fields:
  - import: field nc-field-name
    field_type: import
  - import: field nc-field-label
    field_type: import
  - import: field nc-field-widget
    field_type: import
    extend:
      default: number
  - import: field nc-field-field_type
    field_type: import
    extend:
      default: number
  - import: field nc-field-required
    field_type: import
  - import: field nc-field-default
    field_type: import
    extend: 
      widget: number
  - import: field nc-field-hint
    field_type: import
  - import: field nc-field-value_type
    field_type: import
  - import: field nc-field-min
    field_type: import
  - import: field nc-field-max
    field_type: import
  - import: field nc-field-step
    field_type: import
filter:
  field: field_type
  value: number
create: true
publish: false
hide: false
delete: true
format: yml
extension: yml

editor:
  preview: true
summary: "{{filename}}"

