# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: select
identifier_field: name
label: Select Fields
label_singular: Select Field
collection_type: folder
description: >
  The select widget allows you to pick a string value from a dropdown menu.
folder: "data/netlifycms/fields"
fields:
  - import: field nc-field-name
    field_type: import
  - import: field nc-field-label
    field_type: import
  - import: field nc-field-widget
    field_type: import
    extend:
      default: select
  - import: field nc-field-field_type
    field_type: import
    extend:
      default: select
  - import: field nc-field-required
    field_type: import
  - import: field nc-field-default
    field_type: import
    extend: 
      widget: string
  - import: field nc-field-hint
    field_type: import
  - import: field nc-field-comment
    field_type: import
  - import: field nc-field-pattern
    field_type: import
  - import: field nc-field-options
    field_type: import
  - import: field nc-field-multiple
    field_type: import
  - import: field nc-field-min
    field_type: import
    extend:
      hint: Minimum number of items; ignored if multiple is false.
  - import: field nc-field-max
    field_type: import
    extend:
      hint: Maximum number of items; ignored if multiple is false.
filter:
  field: field_type
  value: select
create: true
publish: false
hide: false
delete: true
format: yml
extension: yml

editor:
  preview: true
summary: "{{filename}}"

