# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: String Fields
identifier_field: name
label: String Fields
label_singular: String Field
collection_type: folder
description: >
  The string widget translates a basic text input to a string value. For larger textarea inputs, use the text widget.
folder: "data/netlifycms/fields"
fields:
  - import: field nc-field-name
    field_type: import
  - import: field nc-field-label
    field_type: import
  - import: field nc-field-widget
    field_type: import
    extend:
      default: string
  - import: field nc-field-required
    field_type: import
  - import: field nc-field-default 
    field_type: import
  - import: field nc-field-hint 
    field_type: import
  - import: field nc-field-comment 
    field_type: import
  - import: field nc-field-pattern  
    field_type: import
filter:
  field: field_type
  value: string
create: true
publish: false
hide: false
delete: true
format: yml
extension: yml

editor:
  preview: true
summary: "{{filename}}"

