# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: text_fields
identifier_field: name
label: Text Fields
label_singular: Text Field
collection_type: folder
description: >
  The text widget takes a multiline text field and saves it as a string. For shorter text inputs, use the string widget.
folder: "data/netlifycms/fields"
fields:
  - import: field nc-field-name
    field_type: import
  - import: field nc-field-label
    field_type: import
  - import: field nc-field-widget
    field_type: import
    extend:
      default: text
  - import: field nc-field-field_type
    field_type: import
    extend:
      default: text
  - import: field nc-field-required
    field_type: import
  - import: field nc-field-default 
    field_type: import
  - import: field nc-field-hint 
    field_type: import
  - import: field nc-field-comment 
    field_type: import
  - import: field nc-field-pattern 
    field_type: import
filter:
  field: field_type
  value: text
create: true
publish: false
hide: false
delete: true
format: yml
extension: yml

editor:
  preview: true
summary: "{{filename}}"

