label: Minimize Collapsed
name: minimize_collapsed
widget: boolean
field_type: boolean
component: field
required: false

hint: When true, collapsing the widget will hide all of it's entries instead of showing summaries.