label: Summary 
name: summary 
widget: string
field_type: string
component: field
hint: "Accepts a string with references to fields like {{name}}, displayed when the object is collapsed in the UI."
required: false