destination: configuration
# This Netlify CMS configuration file was assembled with the assistance of github.com/basa-casa/hugo-module-admin
backend:
  branch: main
  name: test-repo
  repo: basa-casa/hugo-module-bc-nc-admin
collections:
  - import: collection admin-config
    collection_type: import
  - import: collection hugo_configuration
    collection_type: import
local_backend: true
media_folder: assets/img
public_folder: img
site_url: ../
display_url: ../
logo_url: /img/nc-admin.png
