name: Admin Collections Collections
collection_type: set
collections:
  - import: collection nc-folder_collections
    collection_type: import
  - import: collection nc-files_collections
    collection_type: import