label: Import
name: 'import'
component: collection-type
fields:
  - name: "import"
    widget: string
    field_type: string
    hint: "ex: collection" 
  - import: field nc-collection-collection_type
    field_type: import
    extend:
      default: import
  - name: extend
    widget: object
    field_type: object
    required: false
    collapsed: true
    fields:
      - import: field nc-field-name
        extend: 
          required: false
        field_type: import
      - import: field nc-field-label
        field_type: import
      - import: field nc-collection-description
        field_type: import
      - import: field nc-collection-folder
        field_type: import
        extend: 
          required: false
      