label: Filter
name: filter
widget: object
component: collection
fields:
  - import: field nc-collection-field
    field_type: import
  - label: value
    name: value
    widget: string
    field_type: string
    required: false
    hint: The value all of the entries of this collection will have for the
      specified field.
field_type: object
required: false
