label: "Files"
label_singular: File
name: "files" 
widget: "list"
field_type: "list_variable_types"
component: collection
multiple: true
hint: "https://www.netlifycms.org/docs/collection-types#file-collections"
summary: '{{type}}: {{import}}{{file}}'
types:
  - label: Import
    name: import
    hint: Import an existing or in-module file controller to your collection.
    fields:
      - label: import
        name: import
        widget: string
        field_type: text
  - label: File
    name: file
    fields:
      - import: collection nc-files_collection_files.fields
        field_type: import