label: "View Filters" 
name: view_filters
widget: list 
field_type: list 
component: collection
collapsed: true
required: false
hint: "An optional list of predefined view filters to show in the UI."
fields: 
  - import: field nc-field-label
    field_type: import
  - import: field nc-collection-field
    field_type: import
  - import: field nc-field-pattern
    field_type: import