name: frontmatter
slug: hugo-content-frontmatter
widget: list
field_type: list_variable_types
required: false
types:
  - name: aliases
    fields:
      - import: field hugo-content-aliases
        field_type: import