name: collection_sets
# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
description: Create a list of collections to import to CMSs together.
label: Collection Sets
label_singular: Collection Set
collection_type: folder
folder: data/netlifycms/sets
identifier_field: name
format: yml
extension: yml
fields:
  - field_type: import
    import: field nc-field-name
  - field_type: import
    import: field nc-config-collections
create: true
delete: true
publish: true
hide: false
editor:
  preview: true
