name: folder_collections
# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
description: Folder collections represent one or more files with the same
  format, fields, and configuration options, all stored within the same folder
  in the repository. You might use a folder collection for blog posts, product
  pages, author data files, etc.
label: Folder Collections
label_singular: Folder Collection
collection_type: folder
folder: data/netlifycms/collections
filter:
  field: collection_type
  value: folder
identifier_field: name
format: yml
extension: yml
fields:
  - import: field nc-field-name
    field_type: import
    extend:
      comment: Netlify CMS Folder Collection. See
        https://www.netlifycms.org/docs/collection-types#folder-collections
  - import: field nc-collection-description
    field_type: import
  - import: field nc-field-label
    field_type: import
    extend:
      required: true
      hint: Label for the collection in the editor UI.
  - import: field nc-field-label_singular
    field_type: import
  - import: field nc-collection-collection_type
    field_type: import
    extend:
      default: folder
      widget: hidden
  - import: field nc-collection-folder
    field_type: import
  - import: field nc-collection-filter
    field_type: import
    extend: 
      summary: "{{field}}: {{value}}"
      collapsed: true
  - import: field nc-collection-identifier_field
    field_type: import
  - import: field nc-collection-path
    field_type: import
  - import: field nc-collection-slug
    field_type: import
  - import: field nc-collection-format
    field_type: import
  - import: field nc-collection-extension
    field_type: import
  - import: field nc-collection-frontmatter_delimiter
    field_type: import
  - import: field nc-collection-fields
    field_type: import
    extend:
      hint: Create at least one field with name "title" using the String widget, or
        use another field set above as the identifier field. Content collections
        should contain one field named "body" using the Markdown field type.
  - import: field nc-collection-create
    field_type: import
  - import: field nc-collection-delete
    field_type: import
  - import: field nc-collection-publish
    field_type: import
  - import: field nc-collection-hide
    field_type: import
  - import: field nc-collection-preview_path
    field_type: import
  - import: field nc-collection-preview_path_date_field
    field_type: import
  - import: field nc-collection-editor
    field_type: import
  - import: field nc-field-summary
    field_type: import
    extend:
      hint: This setting allows the customization of the collection list view in the
        CMS UI. Enter a string with templates can be used to include values of
        different fields, e.g. {{title}}. This option over-rides the default of
        title field and identifier_field
  - import: field nc-collection-sortable_fields
    field_type: import
  - import: field nc-collection-view_filters
    field_type: import
  - import: field nc-collection-view_groups
    field_type: import
  - import: field nc-collection-media_folder
    field_type: import
  - import: field nc-collection-public_folder
    field_type: import
  - import: field nc-collection-nested
    field_type: import
create: true
delete: true
publish: true
hide: false
editor:
  preview: false
summary: "{{label}} ({{folder}})"