label: List
name: list
widget: object
component: field-type
fields:
  - import: field nc-field-name
    field_type: import
  - import: field nc-field-label
    field_type: import
  - import: field nc-field-widget
    field_type: import
    extend:
      default: list
  - import: field nc-field-required
    field_type: import
  - import: field nc-field-default
    field_type: import
  - import: field nc-field-hint
    field_type: import
  - import: field nc-field-comment
    field_type: import
  - import: field nc-field-pattern
    field_type: import
  - import: field nc-field-label_singular
    field_type: import
  - import: field nc-field-allow_add
    field_type: import
  - import: field nc-field-collapsed
    field_type: import
  - import: field nc-field-summary
    field_type: import
  - import: field nc-field-minimize_collapsed
    field_type: import
  - import: field nc-field-sub_fields
    field_type: import
    extend:
      name: field
      label: field
      required: false
      max: 1
      hint: "Define a single widget to be repeated. "
  - import: field nc-field-sub_fields
    field_type: import
    extend:
      hint: "Define a nested list of single widgets to be repeated."
